name: Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install build dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pillow

      - name: Build site
        env:
          SITE_BASE_URL: https://verininmutfagi.com
          YT_API_KEY: ${{ secrets.YT_API_KEY }}
          PUBLISH_CNAME: ${{ secrets.PUBLISH_CNAME }}
        run: |
          bash scripts/build_all.sh
          python3 scripts/check_links.py --base site --strict
          # optional runtime env config for analytics/contact
          if [ -n "${{ secrets.ANALYTICS_URL }}" ] || [ -n "${{ secrets.ANALYTICS_TOKEN }}" ] || [ -n "${{ secrets.CONTACT_API_URL }}" ] || [ -n "${{ secrets.CONTACT_API_TOKEN }}" ]; then
            {
              echo "window.ANALYTICS_URL = '${{ secrets.ANALYTICS_URL }}';"
              echo "window.ANALYTICS_TOKEN = '${{ secrets.ANALYTICS_TOKEN }}';"
              echo "window.CONTACT_API_URL = '${{ secrets.CONTACT_API_URL }}';"
              echo "window.CONTACT_API_TOKEN = '${{ secrets.CONTACT_API_TOKEN }}';"
            } > site/env.config.js
          fi
          touch site/.nojekyll

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
